DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS CATEGORIES;

DROP TABLE IF EXISTS SUBCATEGORIES;

DROP TABLE IF EXISTS ARTICLES;

DROP TABLE IF EXISTS ARTICLE_HAS_CATEGORIES;

DROP TABLE IF EXISTS COMMENTS;

DROP TABLE IF EXISTS ARTICLE_HAS_REACTION_FROM_USER;

DROP TABLE IF EXISTS COMMENT_HAS_REACTION_FROM_USER;

DROP TABLE IF EXISTS REACTIONS;

DROP TABLE IF EXISTS IMAGES;

DROP TABLE IF EXISTS ARTICLE_HAS_IMAGES;

DROP TABLE IF EXISTS ROLES;

DROP TABLE IF EXISTS USER_HAS_ROLES;

DROP TABLE IF EXISTS PRIVATE_MESSAGES;

DROP TABLE IF EXISTS CHAT_MESSAGES;